server:
  port: 8081

spring:
  application:
    name: market-rest
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  messages:
    basename: messages
    fallback-to-system-locale: false
    use-code-as-default-message: true
  datasource:
    url: jdbc:postgresql://localhost:5433/market
    driverClassName: org.postgresql.Driver
    username: user
    password: password

