version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: market-db
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - market-db-data:/var/lib/postgresql/data

volumes:
  market-db-data:
